config/routes.rb
Workoutlog::Application.routes.draw do

  root 'workouts#index'

  get 'about', to: 'workouts#about'

  resources :workouts do
    resources :exercises
  end

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps, :weight, :distance))
    redirect_to workout_path(@workout)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all.order("date DESC")
  end

  def about
  end
  
  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.create(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def show
    @workout = Workout.find(params[:id])
    @exercise = Exercise.new
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    @workout.update_attributes(workout_params)
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to root_path
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :activity, :mood, :duration)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workoutlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- Viewport meta tag -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">

        <div class="navbar-header">
          <%= link_to 'Workout Loggr', root_path, class: 'navbar-brand' %>
        </div>

        <%= link_to new_workout_path, class: 'btn btn-warning btn-sm' do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          Add a Workout
        <% end %>

      </div>
    </div>
  </div><!-- /.container -->
</nav>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= yield %>

    </div>
  </div>
</div>

<div class="footer">
  <div class="container text-center">
    <%= link_to 'about workout loggr', about_path %>
  </div>
</div>

</body>
</html>

app/views/workouts/about.html.erb
<div id="about" class="text-center">
  <h1>About</h1>
</div>

<br />

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet mollis eros. Praesent pretium massa eget neque auctor, nec interdum mi malesuada. Nullam semper tincidunt turpis, vitae tincidunt tellus ornare placerat.</p>

<p>Integer varius dapibus ultricies. Integer id lacus iaculis, vulputate lectus at, consequat augue. Pellentesque nec tempus ipsum. Integer semper magna mauris, sed vulputate ligula rhoncus ac.</p>

<p>Integer pharetra lacinia dui.</p>

app/views/workouts/edit.html.erb
<div id="edit" class="text-center">
  <h1>Edit this workout</h1>
</div>

<%= simple_form_for @workout do |f| %>
  <br />
  <%= f.input :date %>
  <br />
  <%= f.input :activity, input_html: { class: 'form-control' } %>
  <%= f.input :mood, input_html: { class: 'form-control' } %>
  <%= f.input :duration, input_html: { class: 'form-control' } %>
  <br />
  <%= f.submit 'Update', class: 'btn btn-warning btn-sm' %>
<% end %>

app/views/workouts/index.html.erb
<div id="index">

  <% @workouts.each do |workout| %>
    <div>
      <h2><%= link_to workout.activity, workout_path(workout) %></h2>
      <p><%= workout.date.strftime("%A, %B %d") %></p>
      <p><span>feeling:</span> <%= workout.mood %></p>
      <p><span>length:</span> <%= workout.duration %></p>
    </div>

    <hr />
  <% end %>

</div>

app/views/workouts/new.html.erb
<div id="new" class="text-center">
  <h1>Add a Workout</h1>
</div>

<%= simple_form_for @workout do |f| %>
  <br />
  <%= f.input :date %>
  <br />
  <%= f.input :activity, input_html: { class: 'form-control' } %>
  <%= f.input :mood, input_html: { class: 'form-control' } %>
  <%= f.input :duration, input_html: { class: 'form-control' } %>
  <br />
  <%= f.submit 'Add', class: 'btn btn-warning btn-sm' %>
<% end %>

app/views/workouts/show.html.erb
<div id="show">

  <div>
    <h2><%= @workout.activity %></h2>
    <p><%= @workout.date.strftime("%A, %B %d") %></p>
    <p><span>feeling:</span> <%= @workout.mood %></p>
    <p><span>length:</span> <%= @workout.duration %></p>
    <br />
    <%= link_to 'Edit', edit_workout_path(@workout), class: 'btn btn-warning btn-sm' %>
    <%= link_to 'Delete', workout_path(@workout), method: :delete, data: {confirm: 'Are you sure you want to delete this workout?'},class: 'btn btn-danger btn-sm' %>
  </div>


  <% if @workout.exercises.present? %>
    <hr />

    <h3>Exercises</h3>

    <% @workout.exercises.each do |exercise| %>
        <div>
          <p><span>name:</span> <%= exercise.name %></p>
          <p><span>sets:</span> <%= exercise.sets %></p>
          <p><span>reps:</span> <%= exercise.reps %></p>
          <p><span>weight:</span> <%= exercise.weight %></p>
          <p><span>distance:</span> <%= exercise.distance %></p>
          <br />
        </div>
    <% end %>

  <% end %>


<hr />

<h3>Add Exercise Details</h3>

<%= simple_form_for([@workout, @workout.exercises.build]) do |f| %>
  <%= f.input :name, input_html: { class: 'form-control' } %>
  <%= f.input :sets, input_html: { class: 'form-control' } %>
  <%= f.input :reps, input_html: { class: 'form-control' } %>
  <%= f.input :weight, input_html: { class: 'form-control' } %>
  <%= f.input :distance, input_html: { class: 'form-control' } %>
  <br />
  <%= f.submit 'Add', class: 'btn btn-warning btn-sm' %>
<% end %>



</div>